services:
  nestjs-api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
      minio:
        condition: service_healthy

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=streamtube
      - POSTGRES_PASSWORD=streamtube
      - POSTGRES_DB=streamtube
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamtube"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=streamtube
      - MINIO_ROOT_PASSWORD=streamtube123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 streamtube streamtube123 &&
      mc mb -p local/streamtube-videos &&
      exit 0
      "


